name: Update Profile README

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-readme:
    name: Update recent GitHub activity
    runs-on: ubuntu-latest

    if: github.actor != 'github-actions[bot]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update recent activity
        uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          GH_USERNAME: Lindsey-Mendieta
          CONFIG_FILE: .github/recent-activity.config.yml
